####### PATHS TO SfM RECONSTRUCTION MODEL ########
camera_path: './Colmap/Video_validation/ModelText/cameras.txt'
images_path: './Colmap/Video_validation/ModelText/images.txt'
points_path: './Colmap/Video_validation/ModelText/points3D.txt'
####### PATHS TO IMAGES AND LABELS INSIDE THE FOLDER ########
image_path: './Detection_frames/Video_validation/Images/'
label_path: './Detection_frames/Video_validation/aug/labels/'
####### PATH TO SAVE THE RESULTS (IMAGES AND TRACKING) ########
results_path: './Pseudolabels/Video_ionut/SfmLabels/SfmLabels_skip'
####### LIST DEFINING THE SKIPS VALUE FOR GENERATING PSEUDOLABELS ########
skips: [2, 5]