####### PATHS IMAGES AND YOLO LABELS ########
image_path: './Datasets/Validation/Detection/Images/'
label_path: './Datasets/Validation/Detection/Labels/'
####### DEFINE SKIPS ########
skips: [2, 5]
####### PATH WHERE TO SAVE RESULTS ########
results_path: './Porcodio/Ensomma_skip'